Check all XML for errors before failing

diff --git a/test_course/test_course b/test_course/test_course
--- a/test_course/test_course
+++ b/test_course/test_course
@@ -9,7 +9,8 @@ DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 # Simple xml lint to catch easy stuff
 # Disable eval mode temp to provide a more helpful message
 set +e
-find /course -name \*.xml | while read xml
+failed=false
+while IFS= read -r xml
 do
    xmllint "$xml" --noout;
    rc=$?
@@ -42,13 +43,19 @@ do
            echo "Out of memory error"
            ;;
    esac
-   if [ $? -ne 0 ]; then
-       echo -e "$xml: \033[0;31mBad XML\033[0m"; 
-       break
+   if [ $rc -ne 0 ]; then
+       echo -e "$xml: \033[0;31mBad XML\033[0m"
+       failed=true
+       continue
    fi
    echo -e "$xml: \033[0;32mOK\033[0m"
+done <<< "$(find /course -name \*.xml)"
 
-done
+if $failed; then
+    echo "XML Syntax errors occurred."
+    echo "Please check above for 'Bad XML' and correct them."
+    exit 1
+fi
 set -e
 cd /build/edx-platform
 echo $DIR
